name: tests
on: [pull_request]
jobs:
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install
  #     - run: npm run test
  # e2e-tests:
  #   needs: unit-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install
  #     - run: npx playwright install
  #     - run: npm run test:e2e
  vercel-deploy:
    # needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: vercel -v
